// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sakura_r_serialize
SEXP sakura_r_serialize(SEXP object, SEXP klass_name, SEXP hook_func);
RcppExport SEXP _sakura_sakura_r_serialize(SEXP objectSEXP, SEXP klass_nameSEXP, SEXP hook_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type klass_name(klass_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type hook_func(hook_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(sakura_r_serialize(object, klass_name, hook_func));
    return rcpp_result_gen;
END_RCPP
}
// sakura_r_unserialize
SEXP sakura_r_unserialize(SEXP object, SEXP hook_func);
RcppExport SEXP _sakura_sakura_r_unserialize(SEXP objectSEXP, SEXP hook_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type object(objectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type hook_func(hook_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(sakura_r_unserialize(object, hook_func));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sakura_sakura_r_serialize", (DL_FUNC) &_sakura_sakura_r_serialize, 3},
    {"_sakura_sakura_r_unserialize", (DL_FUNC) &_sakura_sakura_r_unserialize, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sakura(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
