# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sakura_r_serialize <- function(object, klass_name, hook_func) {
    .Call(`_sakura_sakura_r_serialize`, object, klass_name, hook_func)
}

sakura_r_unserialize <- function(object, hook_func) {
    .Call(`_sakura_sakura_r_unserialize`, object, hook_func)
}

